FROM alpine:3.4

# Update
RUN apk update && apk add nodejs && rm -rf /var/cache/apk/* && mkdir /src

RUN npm install -g nodemon

RUN cd /tmp && npm install express socket.io async underscore chartist
RUN mkdir -p /usr/src && cp -a /tmp/node_modules /usr && rm -rf /tmp/*

# add project files
WORKDIR /usr/src
ADD . /usr/src

EXPOSE  8080
CMD ["nodemon", "-L", "index.js"]
